[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = ['cd "administrador de contas/backend" && npm install']

[phases.build]
cmds = ['cd "administrador de contas/backend" && npm run build']

[start]
cmd = 'cd "administrador de contas/backend" && npm start'

